"""
SystemKernel v3.0 — Repo Intake Pipeline.

Deterministic repository assessment without network access.
Evaluates external repos for DIRECT_CLONE, EXTERNAL_EXTENSION,
ARCHITECTURE_REFERENCE, or REJECT decisions.
"""

from v3.intake.repo_intake import (
    DECISION_ARCHITECTURE_REFERENCE,
    DECISION_DIRECT_CLONE,
    DECISION_EXTERNAL_EXTENSION,
    DECISION_REJECT,
    DECISIONS,
    INTENDED_USE_ARCHITECTURE,
    INTENDED_USE_CLAUDE_CODE,
    INTENDED_USE_SYSTEMKERNEL,
    INTENDED_USE_UNKNOWN,
    PRIORITIES,
    PRIORITY_A,
    PRIORITY_B,
    PRIORITY_C,
    PRIORITY_D,
    PRIORITY_S,
    RepoIntakeDecision,
    RepoIntakeInput,
    RepoIntakeReport,
    RepoSignals,
    analyze_local_repo,
    analyze_repo_snapshot,
    compute_report_hash,
    decide_repo_intake,
    write_report,
)

from v3.intake.rules import (
    INTAKE_RULES,
    REPO_TYPE_AGENT_RUNTIME,
    REPO_TYPE_CLAUDE_CODE_EXTENSION,
    REPO_TYPE_CONTEXT_TOOL,
    REPO_TYPE_DOCS_ONLY,
    REPO_TYPE_MEMORY_SYSTEM,
    REPO_TYPE_OBSERVABILITY_TOOL,
    REPO_TYPE_SKILL_SYSTEM,
    REPO_TYPE_UNKNOWN,
    REPO_TYPES,
    IntakeRule,
    apply_rules,
    classify_repo_type,
    get_rules_table,
)

from v3.intake.repo_profiles import (
    PROFILES,
    RepoProfile,
    get_all_profiles,
    get_profile,
    list_profiles,
)

from v3.intake.tool_registry import (
    CLONE_NOW,
    EXTERNAL_EVAL,
    INSPECT_ONLY,
    REFERENCE_ONLY,
    USE_MODE_ARCHITECTURE_REFERENCE,
    USE_MODE_DIRECT_TOOL,
    USE_MODE_EXTERNAL_SERVICE,
    USE_MODE_FORMAT_REFERENCE,
    USE_MODE_SOURCE_REFERENCE,
    USE_MODES,
    ExternalToolEntry,
    ExternalToolRegistry,
    build_registry_from_intake_reports,
    build_registry_from_profiles,
    recommend_clone_order,
    write_registry,
    write_clone_plan,
)

from v3.intake.clone_plan import (
    POST_CLONE_ACTIONS,
    POST_CLONE_EVALUATE_EXTERNAL,
    POST_CLONE_EXTRACT_FORMAT,
    POST_CLONE_INSPECT_ONLY,
    POST_CLONE_NONE,
    POST_CLONE_READ_DOCS,
    POST_CLONE_RUN_CLI_HELP,
    ClonePlan,
    ClonePlanItem,
    create_clone_plan,
    filter_clone_now,
    summarize_plan,
    write_clone_plan_markdown,
)

__all__ = [
    # Decision constants
    "DECISION_DIRECT_CLONE",
    "DECISION_EXTERNAL_EXTENSION",
    "DECISION_ARCHITECTURE_REFERENCE",
    "DECISION_REJECT",
    "DECISIONS",
    # Priority constants
    "PRIORITY_S",
    "PRIORITY_A",
    "PRIORITY_B",
    "PRIORITY_C",
    "PRIORITY_D",
    "PRIORITIES",
    # Intent constants
    "INTENDED_USE_CLAUDE_CODE",
    "INTENDED_USE_SYSTEMKERNEL",
    "INTENDED_USE_ARCHITECTURE",
    "INTENDED_USE_UNKNOWN",
    # Data classes
    "RepoIntakeInput",
    "RepoSignals",
    "RepoIntakeDecision",
    "RepoIntakeReport",
    "IntakeRule",
    "RepoProfile",
    # Analysis
    "analyze_local_repo",
    "analyze_repo_snapshot",
    "decide_repo_intake",
    "compute_report_hash",
    "write_report",
    # Rules
    "INTAKE_RULES",
    "apply_rules",
    "classify_repo_type",
    "get_rules_table",
    # Repo types
    "REPO_TYPE_AGENT_RUNTIME",
    "REPO_TYPE_MEMORY_SYSTEM",
    "REPO_TYPE_OBSERVABILITY_TOOL",
    "REPO_TYPE_CLAUDE_CODE_EXTENSION",
    "REPO_TYPE_SKILL_SYSTEM",
    "REPO_TYPE_CONTEXT_TOOL",
    "REPO_TYPE_DOCS_ONLY",
    "REPO_TYPE_UNKNOWN",
    "REPO_TYPES",
    # Profiles
    "PROFILES",
    "get_profile",
    "list_profiles",
    "get_all_profiles",
    # Tool Registry
    "ExternalToolEntry",
    "ExternalToolRegistry",
    "build_registry_from_intake_reports",
    "build_registry_from_profiles",
    "recommend_clone_order",
    "write_registry",
    "write_clone_plan",
    "USE_MODE_DIRECT_TOOL",
    "USE_MODE_SOURCE_REFERENCE",
    "USE_MODE_EXTERNAL_SERVICE",
    "USE_MODE_FORMAT_REFERENCE",
    "USE_MODE_ARCHITECTURE_REFERENCE",
    "USE_MODES",
    "CLONE_NOW",
    "INSPECT_ONLY",
    "EXTERNAL_EVAL",
    "REFERENCE_ONLY",
    # Clone Plan
    "ClonePlanItem",
    "ClonePlan",
    "create_clone_plan",
    "filter_clone_now",
    "summarize_plan",
    "write_clone_plan_markdown",
    "POST_CLONE_INSPECT_ONLY",
    "POST_CLONE_RUN_CLI_HELP",
    "POST_CLONE_READ_DOCS",
    "POST_CLONE_EVALUATE_EXTERNAL",
    "POST_CLONE_EXTRACT_FORMAT",
    "POST_CLONE_NONE",
    "POST_CLONE_ACTIONS",
]
